<?php
namespace  Src\Lib;

use Illuminate\Database\Eloquent\Model;
use Src\Core\BeanFactory;
use Src\Init\MyDB;

class DBModel extends Model{

    public function __call($method, $parameters)
    {
        return $this->invoke(function() use($method, $parameters){
            return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
        });
    }
    public function save(array $options = [])
    {
        return $this->invoke(function() use($options){
            return parent::save($options);
        });

    }
    private function invoke(callable  $func){
        $mydb=clone BeanFactory::getBean(MyDB::class);
        $obj=$mydb->genConnection();
        try{
            return $func();
        }catch (\Exception $exception){
            var_dump($exception);
            return null;
        }finally{
            $mydb->releaseConnection($obj);
        }
    }


}